networks:
  storages:
    driver: bridge

  server:
    driver: bridge

  loki:
    driver: bridge

services:
  main-app:
    build:
      context: ..
      dockerfile: dev.Dockerfile
    container_name: main-app
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
      - /app/.venv
    networks:
      - storages
      - server
      - loki
    profiles:
      - dev

  main-app-prod:
    build:
      context: ..
      dockerfile: prod.Dockerfile
    container_name: main-app-prod
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env.prod
    volumes:
      - /app/.venv
    networks:
      - storages
      - server
      - loki
    profiles:
      - prod
