version: '3.9'
networks:
  dev:


services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - dev


  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '../nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - main-app
    networks:
      - dev