networks:
  storages:
    driver: bridge

  server:
    driver: bridge

  loki:
    driver: bridge

services:
  main-app:
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
      - /app/.venv
    networks:
      - storages
      - server
      - loki
