version: '3.9'

networks:
  web:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '../config/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - web