services:
  mongodb:
    container_name: chat-mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - storages

volumes:
  dbdata6:

networks:
  storages:
    driver: bridge
