[tool.poetry]
name = "ddd-fastapi"
version = "0.1.0"
description = ""
authors = ["bashar <basharhasan74@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.112.0"}
motor = "^3.5.1"
uvicorn = {extras = ["all"], version = "^0.30.6"}
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
faker = "^28.0.0"
punq = "^0.7.0"
httpx = "^0.27.2"
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
