name: Makefile CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Make
      run: make

    - name: Make Docker Image
      run: make app

    - name: Test App
      run: make test
