name: Makefile CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
      
    - name: Make Docker Image
      run: make app

    - name: Test App
      run: make test
