name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.7"
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install dependencies
        run: uv sync --no-dev
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Set environment variables
        run: |
          cp .env.example .env  # Copy .env.example to .env if .env is not available
          cat .env  # Verify the .env file content

      - name: Test with pytest
        run: uv run pytest
