name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --no-dev
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Set environment variables
        env:
          API_PORT: ${{ secrets.API_PORT }}
          PYTHONPATH: ${{ secrets.PYTHONPATH }}
          MONGO_DB_CONNECTION_URI: ${{ secrets.MONGO_DB_CONNECTION_URI }}
          MONGO_DB_ADMIN_USERNAME: ${{ secrets.MONGO_DB_ADMIN_USERNAME }}
          MONGO_DB_ADMIN_PASSWORD: ${{ secrets.MONGO_DB_ADMIN_PASSWORD }}
        run: |
          echo "Environment variables set."

      - name: Test with pytest
        run: uv run pytest
