name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --no-dev
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Set environment variables
        run: |
          cp .env.example .env  # Copy .env.example to .env if .env is not available
          cat .env  # Verify the .env file content

      - name: Test with pytest
        run: uv run pytest
