name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r pyproject.toml
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Create env file
        run: |
          touch .env
          echo API_PORT=${{ secrets.API_PORT }} >> .env
          echo PYTHONPATH=${{ secrets.PYTHONPATH }} >> .env
          echo MONGO_DB_CONNECTION_URI=${{ secrets.MONGO_DB_CONNECTION_URI }} >> .env
          echo MONGO_DB_ADMIN_USERNAME=${{ secrets.MONGO_DB_ADMIN_USERNAME }} >> .env
          echo MONGO_DB_ADMIN_PASSWORD=${{ secrets.MONGO_DB_ADMIN_PASSWORD }} >> .env
          cat .env

      - name: Test with pytest
        run: pytest
